### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by bfodeke**
Updated list of examples to make it a bit easier to read

### CODE REVIEW

**Comment by bfodeke** [comment]
I'll, update coming shortly

**Comment by e0ipso** [comment]
As a curiosity. Can I ask you where you learned about this project? I am about to start promoting it but I haven't started yet. My guess is that it showed in your YouTube feed, is that it?

**Comment by bfodeke** [comment]
A team member dropped the youtube link in Slack this morning.

He and I did a presentation at Drupalcamp Asheville about contentacms https://www.youtube.com/watch?v=-ZoIqUd6P5o

I was really excited when I heard of this.

**Comment by bfodeke** [comment]
PR updated!

**Pull request merged**
